name: amazee.io Umami Search
type: amazee.io
description: Adds AI search on top of Umami using Amazee.io provider.
input:
  postgres_db_default_database:
    data_type: string
    description: The Amazee.io PostGreSQL default database.
    prompt:
      method: ask
      arguments:
        question: 'The Amazee.io PostGreSQL default database:'
    default:
      source: value
      value: ''
install:
  - key
  - block
  - ai
  - ai_provider_amazeeio
  - ai_assistant_api
  - ai_chatbot
  - ai_search
  - ai_vdb_provider_postgres
  - search_api
  - search_api_db
config:
  actions:
    search_api.server.umami_recipe_server:
      setupVdbServerWithDefaults:
        langcode: en
        status: true
        dependencies:
          module:
            - ai_search
        id: umami_recipe_server
        name: 'Umami Recipe Server'
        description: 'This is the server part to be able to search for Umami recipes.'
        backend: search_api_ai_search
        backend_config:
          chat_model: amazeeio__chat
          database: amazeeio_vector_db
          database_settings:
            database_name: ${postgres_db_default_database}
            collection: recipe_server
            metric: cosine_similarity
          embedding_strategy: contextual_chunks
          embedding_strategy_configuration:
            chunk_size: '2048'
            chunk_min_overlap: '100'
            contextual_content_max_percentage: '30'
          embedding_strategy_details: ''
    search_api.index.umami_recipe_index:
      setupVdbIndex:
        langcode: en
        status: true
        dependencies:
          config:
            - core.entity_view_mode.node.full
            - field.storage.node.field_difficulty
            - field.storage.node.field_tags
            - search_api.server.umami_recipe_server
          module:
            - node
        id: umami_recipe_index
        name: 'Umami Recipe Index'
        description: 'This holds the inex for the Umami Recipe Searcher.'
        read_only: false
        field_settings:
          field_difficulty:
            label: Difficulty
            datasource_id: 'entity:node'
            property_path: field_difficulty
            type: string
            dependencies:
              config:
                - field.storage.node.field_difficulty
          name:
            label: 'Tags » Taxonomy term » Name'
            datasource_id: 'entity:node'
            property_path: 'field_tags:entity:name'
            type: string
            dependencies:
              config:
                - field.storage.node.field_tags
              module:
                - taxonomy
          rendered_item:
            label: 'Rendered HTML output'
            property_path: rendered_item
            type: text
            configuration:
              roles:
                - anonymous
              view_mode:
                'entity:node':
                  ':default': full
                  recipe: full
          title:
            label: Title
            datasource_id: 'entity:node'
            property_path: title
            type: string
            dependencies:
              module:
                - node
          url:
            label: URI
            property_path: search_api_url
            type: string
            configuration:
              absolute: true
        datasource_settings:
          'entity:node':
            bundles:
              default: false
              selected:
                - recipe
            languages:
              default: false
              selected:
                - en
        processor_settings:
          add_url: {  }
          aggregated_field: {  }
          custom_value: {  }
          entity_type: {  }
          language_with_fallback: {  }
          rendered_item: {  }
        tracker_settings:
          default:
            indexing_order: fifo
        options:
          cron_limit: 50
          delete_on_fail: true
          index_directly: true
          track_changes_in_references: true
        server: umami_recipe_server
